############################################################
# +------------------------------------------------------+ #
# |                  Main Configurations                 | #
# +------------------------------------------------------+ #
############################################################

raid:
  # The number of waves must be at HIGHER than the default number of waves based on the
  # world's difficulty (which is 3 for EASY, 5 for NORMAL, 7 for HARD). The length of the
  # arrays under the `mobs` configuration section below must also be at least the number
  # of waves. Each wave must have at least one raider.
  waves: 20
  # To disable sounds, leave the sound fields blank.
  sounds:
    summon: ITEM_TRIDENT_THUNDER
    victory: ENTITY_ENDER_DRAGON_DEATH
    defeat: ENTITY_ENDER_DRAGON_DEATH
  announce-waves:
    title: true
    message: false
  # Do not add any other mobs, they will not spawn...
  mobs:
    pillager: [5, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10]
    vindicator: [0, 3, 5, 5, 5, 5, 5, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10]
    ravager: [0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3]
    witch: [0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]
    evoker: [0, 0, 0, 0, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4]
    illusioner: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3]

hero-of-the-village:
  # Level 12 is enough to grant a player a cost of 1 emerald for any default trades.
  level: 12
  # In minutes.
  duration: 40

############################################################
# +------------------------------------------------------+ #
# |                   Trigger Mechanism                  | #
# +------------------------------------------------------+ #
#  We present the following triggering mechanisms. It's    #
#  advised that you only enable one of them at any point   #
#  in time although they should technically work with      #
#  each other.                                             #
############################################################

trigger:
  # Dropping summoning items in lava will trigger a large raid if in vicinity of a
  # village.
  drop-item-in-lava:
    enabled: true
    # Note: The summoning item stated here will not lose its primary functionality. For
    # example, totems will still be consumed and revive the player holding it.
    item:
      # Totem by default if the input material is invalid/left blank. Instead of totems,
      # you can use rarer items for summoning (e.g NETHER_STAR).
      material: TOTEM_OF_UNDYING
      display-name: "&6Large Raid Summoner"
      lore:
        - "&5Drop the item into lava in a village"
        - "&5to summon a large raid!"
      custom-model-data:
      # Avoid using armor/tools for material if this is enabled. It applies mending to
      # the item for the glint.
      enchantment-glint: true
