main: com.solarrabbit.largeraids.LargeRaids
name: LargeRaids
version: ${project.version}
author: SolarRabbit
api-version: 1.14

commands:
  lrreload:
    description: Reloads LargeRaids plugin configurations.
    permission: largeraids.admin
  lrstart:
    description: Start a large raid.
    permission: largeraids.admin
  lrstop:
    description: Stop a large raid.
    permission: largeraids.admin
  lrgive:
    description: Give a player the summoning item.
    usage: /<command> <player> [amount]
    permission: largeraids.admin
  lrcenters:
    description: Adds an artificial village at player's location.
    usage: /<command> <add|remove|list> [name]

permissions:
  largeraids.admin:
    description: Allow access to LargeRaids commands.
    default: op
