main: com.solarrabbit.largeraids.LargeRaids
name: LargeRaids
version: ${project.version}
author: SolarRabbit
api-version: 1.14

softdepend: [PlaceholderAPI]

commands:
  lrreload:
    description: Reloads LargeRaids plugin configurations.
    permission: largeraids.admin
  lrstart:
    description: Start a large raid.
    usage: /<command> [player]
    permission: largeraids.admin
  lrstop:
    description: Stop a large raid.
    usage: /<command> [player]
    permission: largeraids.admin
  lrgive:
    description: Give a player the summoning item.
    usage: /<command> <player> [amount]
    permission: largeraids.admin
  lrcenters:
    description: Managing artificial villages.
    usage: /<command> [add | remove] [name]
    permission: largeraids.admin

permissions:
  largeraids.admin:
    description: Allow access to LargeRaids commands.
    default: op
